site_name: Tembici
repo_url: https://github.com/Requisitos-de-Software/2021.2-Tembici

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: pink
    accent: indigo
  favicon: assets/tembiciFavIcon.ico
  logo: assets/tembiciAlt.png
  features:
    - navigation.tabs
extra:
  homepage: https://www.tembici.com.br

nav: 
  - Início: ./index.md
  - Apresentações: 
    - Primeira Apresentação: ./apresentacoes/apresentacao1.md
    - Segunda Apresentação: ./apresentacoes/apresentacao2.md
  - Planejamento: 
    - Metodologia: ./planejamento/metodologia.md
    - Ferramentas Utilizadas: ./planejamento/ferramentas.md
    - Cronograma: ./planejamento/cronograma.md
    - Políticas: ./planejamento/politicas.md
  - Pré-Rastreabilidade: 
    - Rich Picture: ./pre-rastreabilidade/rich-picture.md
    - 5W2H: ./pre-rastreabilidade/5w2h.md
  - Elicitação:
    - Técnicas: 
      - Instrospecção: ./elicitacao/tecnicas/introspeccao.md
      - Questionário: ./elicitacao/tecnicas/questionario.md
      - Brainstorm: ./elicitacao/tecnicas/brainstorm.md
    - Priorização: 
        - MosCoW: ./elicitacao/priorizacao/moscow.md
    - Personas: ./elicitacao/personas.md
  - Modelagem:
    - Casos de Uso: ./modelagem/casos_de_uso.md
    - Cenários: ./modelagem/cenarios.md
    - Especificação Suplementar: ./modelagem/especificacao_suplementar.md
    - Léxicos: ./modelagem/lexicos.md
    
markdown_extensions:
  - attr_list
  - md_in_html
