site_name: Tembici
theme:
  name: material
  palette:
    primary: pink
    accent: indigo
  favicon: assets/tembiciFavIcon.ico
  logo: assets/tembiciAlt.png
  features:
    - navigation.tabs
extra:
  homepage: https://www.tembici.com.br

nav: 
  - Início: ./index.md
  - Apresentações: ./apresentacoes/apresentacoes.md
  - Planejamento: ./planejamento/planejamento.md
  - Pré-Rastreabilidade: ./pre-rastreabilidade/pre-rastreabilidade.md
  - Elicitação:
    - Personas: ./elicitacao/personas.md
    - Tecnicas: 
      - Instrospecção: ./elicitacao/introspeccao.md
      - Questionario: ./elicitacao/questionario.md
      - Brainstorm: ./elicitacao/brainstorm.md
  - Priorização: ./priorizacao/priorizacao.md

markdown_extensions:
  - attr_list
  - md_in_html